// Code generated by scripts/helper/generate-provider-probes.cjs; DO NOT EDIT.

package providerprobe

// Definition is one allowlisted provider version probe.
type Definition struct {
	Provider    string
	Command     string
	VersionArgs []string
}

var Registry = []Definition{
	{Provider: "codex", Command: "codex", VersionArgs: []string{"--version"}},
	{Provider: "claude", Command: "claude", VersionArgs: []string{"--version"}},
	{Provider: "gemini", Command: "gemini", VersionArgs: []string{"--version"}},
	{Provider: "antigravity", Command: "agy", VersionArgs: []string{"--version"}},
	{Provider: "opencode", Command: "opencode", VersionArgs: []string{"--version"}},
	{Provider: "cursor", Command: "cursor-agent", VersionArgs: []string{"--version"}},
	{Provider: "copilot", Command: "copilot", VersionArgs: []string{"version"}},
	{Provider: "qwen", Command: "qwen", VersionArgs: []string{"--version"}},
	{Provider: "amp", Command: "amp", VersionArgs: []string{"--version"}},
	{Provider: "crush", Command: "crush", VersionArgs: []string{"--version"}},
	{Provider: "goose", Command: "goose", VersionArgs: []string{"--version"}},
	{Provider: "aider", Command: "aider", VersionArgs: []string{"--version"}},
}
